;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2009 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.model)

(def localization hu
  (class-name.attachment "csatolás")
  (class-name.audited-object "auditált objektum")
  (class-name.cluster "cluster")
  (class-name.cluster-node "cluster node")
  (class-name.cluster-node-session "cluster node session")
  (class-name.desktop "asztal")
  (class-name.encrypted-password-authentication-instrument "jelszavas beléptető eszköz")
  (class-name.object-with-attachments "csatolásokkal renderlező objektum")
  (class-name.persistent-argument "paraméter")
  (class-name.persistent-component "komponens")
  (class-name.persistent-function "függvény")
  (class-name.persistent-log-entry "napló bejegyzés")
  (class-name.subject-preferences "beállítások")
  (class-name.topic "téma")
  (class-name.topic-post "bejegyzés")
  (diagram-name.authentication-diagram "beléptető rendszer")
  (diagram-name.cluster-diagram "fürtözött rendszer")
  (level.+debug+ "részletes")
  (level.+dribble+ "sustorgás")
  (level.+error+ "hiba")
  (level.+fatal+ "fatális hiba")
  (level.+info+ "információ")
  (level.+warn+ "figyelmeztetés")
  (requested-operation-mode.maintenance "karbantartás")
  (requested-operation-mode.mixed "kevert")
  (requested-operation-mode.normal "normál üzem")
  (requested-operation-mode.shutdown "leállítva")
  (slot-name.body "törzs")
  (slot-name.category "categória")
  (slot-name.children-topics "altémák")
  (slot-name.code "kód")
  (slot-name.content "tartalom")
  (slot-name.created-at "létrehozás időpontja")
  (slot-name.created-in "létrehozva")
  (slot-name.created-instances "létrehozott példányok")
  (slot-name.description "leírás")
  (slot-name.display-command-labels "parancsikonok szövegének megjelenítése")
  (slot-name.dynamic-space-usage "dinamikus memória foglaltság")
  (slot-name.host-name "szerver név")
  (slot-name.last-activity-at "utolsó aktivitás időpontja")
  (slot-name.last-modified-at "utolsó módosítás időpontja")
  (slot-name.last-modified-in "utoljára módosítva")
  (slot-name.last-modified-instances "utoljára módosított példányok")
  (slot-name.last-started-session "legutóbbi üzemelés")
  (slot-name.level "szint")
  (slot-name.load-average "terhelés")
  (slot-name.logged-at "bejegyezés időpontja")
  (slot-name.mail-relay-host-name "mail szerver neve")
  (slot-name.maximum-drill-down-depth "maximális lefúrási mélység")
  (slot-name.mime-type "MIME típus")
  (slot-name.name "név")
  (slot-name.password "jelszó")
  (slot-name.password-expires-at "jelszó lejárati időpontja")
  (slot-name.persistent-process-scheduler-poll-time "perzisztens folyamat ütemező várakozási idő")
  (slot-name.persistent-process-worker-count "perzisztens folyamat feldolgozók száma")
  (slot-name.publish-at "megjelenés ideje")
  (slot-name.requested-operation-mode "működési mód")
  (slot-name.salt "jelszó só")
  (slot-name.shutdown-at "leállítás időpontja")
  (slot-name.startup-at "elindítás időpontja")
  (slot-name.subject "alany")
  (slot-name.the-type "típus")
  (slot-name.timezone "időzóna")
  (slot-name.title "cím")
  (slot-name.web-session-count "web session-ök száma")
  (slot-name.web-worker-count "web feldolgozók száma")
  (slot-name.zip-code "irányítószám"))
