;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2009 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.model)

(def localization hu
  (class-name.address "cím")
  (class-name.attachment "csatolás")
  (class-name.audited-object "auditált objektum")
  (class-name.cluster "cluster")
  (class-name.cluster-node "cluster node")
  (class-name.cluster-node-session "cluster node session")
  (class-name.country "ország")
  (class-name.county "megye")
  (class-name.desktop "asztal")
  (class-name.encrypted-password-authentication-instrument "jelszavas beléptető eszköz")
  (class-name.object-with-attachments "csatolásokkal renderlező objektum")
  (class-name.persistent-argument "paraméter")
  (class-name.persistent-component "komponens")
  (class-name.persistent-function "függvény")
  (class-name.persistent-log-entry "napló bejegyzés")
  (class-name.public-place "közterület")
  (class-name.public-place-type "közterület típus")
  (class-name.settlement "település")
  (class-name.subject-preferences "beállítások")
  (class-name.topic "téma")
  (class-name.topic-post "bejegyzés")
  (diagram-name.authentication-diagram "beléptető rendszer")
  (diagram-name.cluster-diagram "fürtözött rendszer")
  (level.+debug+ "részletes")
  (level.+dribble+ "sustorgás")
  (level.+error+ "hiba")
  (level.+fatal+ "fatális hiba")
  (level.+info+ "információ")
  (level.+warn+ "figyelmeztetés")
  (requested-operation-mode.maintenance "karbantartás")
  (requested-operation-mode.mixed "kevert")
  (requested-operation-mode.normal "normál üzem")
  (requested-operation-mode.shutdown "leállítva")
  (slot-name.body "törzs")
  (slot-name.category "categória")
  (slot-name.children-topics "altémák")
  (slot-name.code "kód")
  (slot-name.content "tartalom")
  (slot-name.created-at "létrehozás időpontja")
  (slot-name.created-in "létrehozva")
  (slot-name.created-instances "létrehozott példányok")
  (slot-name.description "leírás")
  (slot-name.dialing-code "előhívó szám")
  (slot-name.display-command-labels "parancsikonok szövegének megjelenítése")
  (slot-name.door "ajtó")
  (slot-name.dynamic-space-usage "dinamikus memória foglaltság")
  (slot-name.floor-number "emelet")
  (slot-name.full-address "teljes cím")
  (slot-name.host-name "szerver név")
  (slot-name.house-number "házszám")
  (slot-name.last-activity-at "utolsó aktivitás időpontja")
  (slot-name.last-modified-at "utolsó módosítás időpontja")
  (slot-name.last-modified-in "utoljára módosítva")
  (slot-name.last-modified-instances "utoljára módosított példányok")
  (slot-name.last-started-session "legutóbbi üzemelés")
  (slot-name.latitude "szélességi fok")
  (slot-name.level "szint")
  (slot-name.load-average "terhelés")
  (slot-name.logged-at "bejegyezés időpontja")
  (slot-name.longitude "hosszúsági fok")
  (slot-name.mail-relay-host-name "mail szerver neve")
  (slot-name.maximum-drill-down-depth "maximális lefúrási mélység")
  (slot-name.mime-type "MIME típus")
  (slot-name.name "név")
  (slot-name.password "jelszó")
  (slot-name.password-expires-at "jelszó lejárati időpontja")
  (slot-name.persistent-process-scheduler-poll-time "perzisztens folyamat ütemező várakozási idő")
  (slot-name.persistent-process-worker-count "perzisztens folyamat feldolgozók száma")
  (slot-name.publish-at "megjelenés ideje")
  (slot-name.requested-operation-mode "működési mód")
  (slot-name.salt "jelszó só")
  (slot-name.short-address "rövid cím")
  (slot-name.shutdown-at "leállítás időpontja")
  (slot-name.startup-at "elindítás időpontja")
  (slot-name.subject "alany")
  (slot-name.the-type "típus")
  (slot-name.timezone "időzóna")
  (slot-name.title "cím")
  (slot-name.web-session-count "web session-ök száma")
  (slot-name.web-worker-count "web feldolgozók száma")
  (slot-name.zip-code "irányítószám")
  (topic-post.subject "tárgy")
  (short-address (address)
    ;; TODO these slobops shouldn't be needed, fix slots instead
    (bind ((public-place (when (slot-boundp address 'public-place) (public-place-of address)))
           (settlement (when (slot-boundp public-place 'settlement) (settlement-of public-place))))
      (string+ (name-of settlement)
               ", "
               (when public-place
                 (name-of public-place))
               " "
               (when public-place
                 (name-of (public-place-type-of public-place)))
               " "
               (when address
                 (princ-to-string (house-number-of address))))))
  (full-address (address)
    (bind ((public-place (public-place-of address))
           (settlement (settlement-of public-place)))
      (string+ (name-of (country-of (county-of settlement)))
               " "
               (princ-to-string (zip-code-of settlement))
               " "
               (name-of settlement)
               ", "
               (name-of public-place)
               " "
               (name-of (public-place-type-of public-place))
               " "
               (princ-to-string (house-number-of address))
               " "
               (princ-to-string (floor-number-of address))
               "/"
               (princ-to-string (door-of address))))))
