;;; -*- mode: Lisp; Syntax: Common-Lisp; -*-
;;;
;;; Copyright (c) 2009 by the authors.
;;;
;;; See LICENCE for details.

(in-package :hu.dwim.model)

(def entity public-place-type ()
  ((name :type standard-text :primary #t :reference #t)))

(def function create-public-place-types (country-code &optional public-place-types)
  (dolist (data (or public-place-types
                    (symbol-value (concatenate-symbol (find-package :hu.dwim.model)
                                                      "*" country-code "-public-place-type-data*"))))
    (make-public-place-type :name (pop data))))

(def function create-hu-public-place-types ()
  (create-public-place-types 'hu))

(def special-variable *hu-public-place-type-data*
  '(("akna")
    ("aluljáró")
    ("alsóhegy")
    ("alsósor")
    ("alsó")
    ("autópálya")
    ("bánya oldal")
    ("bástya")
    ("bástyája")
    ("csarnok")
    ("csárda")
    ("céltelepülés")
    ("domb")
    ("dűlő")
    ("dűlősor")
    ("dűlőút")
    ("erőd")
    ("elágazás")
    ("emlékút")
    ("erdő")
    ("erdészház")
    ("erdősor")
    ("felső")
    ("felsőhegy")
    ("felsősor")
    ("fennsík")
    ("fok")
    ("forduló")
    ("fasor")
    ("fasora")
    ("főtér")
    ("főút")
    ("garázssor")
    ("gulyakút")
    ("gyártelep")
    ("gát")
    ("gátőrház")
    ("határátkelő")
    ("határsor")
    ("határút")
    ("hegy")
    ("hegyalja")
    ("hídfő")
    ("hát")
    ("híd")
    ("ipartelep")
    ("játszótér")
    ("kapu")
    ("kertsor")
    ("kert")
    ("kerület")
    ("kioszk")
    ("kishajtás")
    ("kikötő")
    ("kiserdő")
    ("kitérő")
    ("kocsiszín")
    ("kolónia")
    ("körút")
    ("korzó")
    ("kultúrpark")
    ("kertek")
    ("kutyor")
    ("körzet")
    ("kőbánya")
    ("környék")
    ("körtér")
    ("körvasútsor")
    ("körönd")
    ("köz")
    ("középhegy")
    ("középsor")
    ("kút")
    ("lakótelep")
    ("lejtő")
    ("lejáró")
    ("liget")
    ("ligete")
    ("laktanya")
    ("lépcsősor")
    ("lépcső")
    ("major")
    ("malom")
    ("metróállomás")
    ("mező")
    ("mélyút")
    ("oldal")
    ("orom")
    ("park")
    ("pavilonsor")
    ("piac")
    ("parkerdő")
    ("piactér")
    ("pihenő")
    ("pincesor")
    ("parkja")
    ("part")
    ("puszta")
    ("pályaudvar")
    ("repülőtér")
    ("rakpart")
    ("rét")
    ("sora")
    ("sor")
    ("sugárút")
    ("szakasz")
    ("sziget")
    ("szőlőskert")
    ("szél")
    ("szőlő")
    ("szőlőhegy")
    ("szőlők")
    ("sétány")
    ("tag")
    ("tér")
    ("tere")
    ("tető")
    ("telep")
    ("tanya")
    ("tanyák")
    ("település")
    ("turistaház")
    ("tábor")
    ("tó")
    ("udvar")
    ("ugarok")
    ("utcája")
    ("út")
    ("utak")
    ("utca")
    ("útja")
    ("vasúti megálló")
    ("vasútállomás")
    ("völgy")
    ("vízmű")
    ("vár")
    ("várkert")
    ("város")
    ("vásártér")
    ("végállomás")
    ("völgye")
    ("zsilip")
    ("zug")
    ("zártkert")
    ("állomás")
    ("árok")
    ("átjáró")
    ("öböl")
    ("ösvény")
    ("övezet")
    ("újsor")
    ("újtelep")
    ("útfél")
    ("üdülőtelep")
    ("üdülőpart")
    ("nincs")
    ("kislakások")
    ("őrház")
    ("ház")
    ("vesszős")
    ("vadászlak")
    ("üdülő")
    ("bérc")
    ("gyár")
    ("víz")
    ("kőkötő")
    ("kőlápa")
    ("egyetemváros")
    ("torok")
    ("tüdőszanatórium")
    ("iskola")
    ("föld")
    ("kültelek")
    ("vadászház")
    ("bánya")
    ("szentkút")
    ("állatkert")
    ("gáztároló")
    ("kunyhó")
    ("kerekalja")
    ("külterület")
    ("szennyvíztelep")
    ("sportpálya")
    ("cigánytelep")
    ("palánk")))
